Repository LedgerSync/ledger_sync, pull requests merged in 2019-10, with the labels that each got.

#39 Add dirty tracking for resources
  lib/ledger_sync/resource.rb
  lib/ledger_sync/resource_attribute.rb
  lib/ledger_sync/resource_attribute/dirty_mixin.rb
  lib/ledger_sync/resource_attribute/mixin.rb
  lib/ledger_sync/resource_attribute_set.rb
  spec/resources/dirty_spec.rb
  spec/serializable/operation_spec.rb
  spec/serializable/resource_spec.rb
  spec/serializable/result_spec.rb
Labels: enhancement

#46 Fix dirty changes
  lib/ledger_sync/resource.rb
  lib/ledger_sync/resource_attribute.rb
  lib/ledger_sync/resource_attribute/mixin.rb
  lib/ledger_sync/resource_attribute/reference/many.rb
  lib/ledger_sync/resource_attribute/reference/one.rb
  lib/ledger_sync/util/resources_builder.rb
  spec/adaptors/operation_contract_spec.rb
  spec/resources/dirty_spec.rb
  spec/serializable/operation_spec.rb
  spec/serializable/resource_spec.rb
  spec/serializable/result_spec.rb
Labels: bug

#52 Remove Sync class and update README
  README.md
  lib/ledger_sync.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/searcher.rb
  lib/ledger_sync/result.rb
  lib/ledger_sync/sync.rb
  spec/adaptors/quickbooks_online/operations/expense/create_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/update_spec.rb
  spec/adaptors/quickbooks_online/util/adaptor_error_parser_spec.rb
  spec/adaptors/quickbooks_online/util/operation_error_parser_spec.rb
  spec/integrations/quickbooks_online/accounts/create_spec.rb
  spec/integrations/quickbooks_online/accounts/find_spec.rb
  spec/integrations/quickbooks_online/accounts/update_spec.rb
  spec/integrations/quickbooks_online/accounts/upsert_spec.rb
  spec/integrations/quickbooks_online/customers/create_spec.rb
  spec/integrations/quickbooks_online/customers/find_spec.rb
  spec/integrations/quickbooks_online/customers/update_spec.rb
  spec/integrations/quickbooks_online/customers/upsert_spec.rb
  spec/integrations/quickbooks_online/expenses/create_spec.rb
  spec/integrations/quickbooks_online/expenses/find_spec.rb
  spec/integrations/quickbooks_online/expenses/update_spec.rb
  spec/integrations/quickbooks_online/expenses/upsert_spec.rb
  spec/integrations/quickbooks_online/payments/create_spec.rb
  spec/integrations/quickbooks_online/payments/find_spec.rb
  spec/integrations/quickbooks_online/payments/update_spec.rb
  spec/integrations/quickbooks_online/payments/upsert_spec.rb
  spec/integrations/quickbooks_online/vendors/create_spec.rb
  spec/integrations/quickbooks_online/vendors/find_spec.rb
  spec/integrations/quickbooks_online/vendors/update_spec.rb
  spec/integrations/quickbooks_online/vendors/upsert_spec.rb
  spec/integrations/test/accounts/create_spec.rb
  spec/integrations/test/accounts/find_spec.rb
  spec/integrations/test/accounts/update_spec.rb
  spec/integrations/test/accounts/upsert_spec.rb
  spec/integrations/test/customers/create_spec.rb
  spec/integrations/test/customers/find_spec.rb
  spec/integrations/test/customers/update_spec.rb
  spec/integrations/test/customers/upsert_spec.rb
  spec/integrations/test/expenses/create_spec.rb
  spec/integrations/test/expenses/find_spec.rb
  spec/integrations/test/expenses/update_spec.rb
  spec/integrations/test/expenses/upsert_spec.rb
  spec/integrations/test/payments/create_spec.rb
  spec/integrations/test/payments/find_spec.rb
  spec/integrations/test/payments/update_spec.rb
  spec/integrations/test/payments/upsert_spec.rb
  spec/integrations/test/vendors/create_spec.rb
  spec/integrations/test/vendors/find_spec.rb
  spec/integrations/test/vendors/update_spec.rb
  spec/integrations/test/vendors/upsert_spec.rb
  spec/serializable/result_spec.rb
  spec/serializable/sync_spec.rb
  spec/support/input_helpers.rb
  spec/support/quickbooks_helpers.rb
  spec/sync_spec.rb
Labels: enhancement

#53 Rmeove sub operations from operations
  lib/ledger_sync/adaptors/quickbooks_online/account/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/account/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/account/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  lib/ledger_sync/adaptors/quickbooks_online/customer/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/customer/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/customer/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation.rb
  lib/ledger_sync/adaptors/quickbooks_online/payment/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/payment/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/payment/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/update.rb
  lib/ledger_sync/adaptors/test/account/operations/create.rb
  lib/ledger_sync/adaptors/test/account/operations/find.rb
  lib/ledger_sync/adaptors/test/account/operations/update.rb
  lib/ledger_sync/adaptors/test/adaptor.rb
  lib/ledger_sync/adaptors/test/customer/operations/create.rb
  lib/ledger_sync/adaptors/test/customer/operations/find.rb
  lib/ledger_sync/adaptors/test/customer/operations/update.rb
  lib/ledger_sync/adaptors/test/expense/operations/create.rb
  lib/ledger_sync/adaptors/test/expense/operations/find.rb
  lib/ledger_sync/adaptors/test/expense/operations/update.rb
  lib/ledger_sync/adaptors/test/payment/operations/create.rb
  lib/ledger_sync/adaptors/test/payment/operations/find.rb
  lib/ledger_sync/adaptors/test/payment/operations/update.rb
  lib/ledger_sync/adaptors/test/vendor/operations/create.rb
  lib/ledger_sync/adaptors/test/vendor/operations/find.rb
  lib/ledger_sync/adaptors/test/vendor/operations/update.rb
  spec/adaptors/quickbooks_online/adaptor_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/create_spec.rb
Labels: bug

#55 Remove upserts
  README.md
  lib/ledger_sync/adaptors/operation.rb
  lib/ledger_sync/adaptors/quickbooks_online/account/operations/upsert.rb
  lib/ledger_sync/adaptors/quickbooks_online/customer/operations/upsert.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/upsert.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation.rb
  lib/ledger_sync/adaptors/quickbooks_online/payment/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/payment/operations/upsert.rb
  lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/upsert.rb
  lib/ledger_sync/adaptors/test/account/operations/upsert.rb
  lib/ledger_sync/adaptors/test/customer/operations/upsert.rb
  lib/ledger_sync/adaptors/test/expense/operations/update.rb
  lib/ledger_sync/adaptors/test/expense/operations/upsert.rb
  lib/ledger_sync/adaptors/test/payment/operations/update.rb
  lib/ledger_sync/adaptors/test/payment/operations/upsert.rb
  lib/ledger_sync/adaptors/test/vendor/operations/upsert.rb
  spec/adaptors/operation_spec.rb
  spec/adaptors/quickbooks_online/operations/account/upsert_spec.rb
  spec/adaptors/quickbooks_online/operations/customer/upsert_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/create_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/update_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/upsert_spec.rb
  spec/adaptors/quickbooks_online/operations/payment/upsert_spec.rb
  spec/adaptors/quickbooks_online/operations/vendor/upsert_spec.rb
  spec/adaptors/test/operations/account/upsert_spec.rb
  spec/adaptors/test/operations/customer/upsert_spec.rb
  spec/adaptors/test/operations/expense/upsert_spec.rb
  spec/adaptors/test/operations/payment/upsert_spec.rb
  spec/adaptors/test/operations/vendor/upsert_spec.rb
Labels: enhancement

#56 Update README
  README.md
Labels: documentation, enhancement

#57 Fix typo in readme
  README.md
Labels: bug

#63 Update documentation
  README.md
  lib/ledger_sync/adaptors/searcher.rb
Labels: documentation, enhancement

#65 Move active_model to runtime dependencies
  Gemfile.lock
  ledger_sync.gemspec
Labels: bug

#64 Add refresh_token_expires_at to adaptor and attributes to save
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  spec/adaptors/quickbooks_online/adaptor_spec.rb
  spec/integrations/quickbooks_online/accounts/create_spec.rb
  spec/integrations/quickbooks_online/accounts/find_spec.rb
  spec/integrations/quickbooks_online/accounts/searcher_spec.rb
  spec/integrations/quickbooks_online/accounts/update_spec.rb
  spec/integrations/quickbooks_online/adaptor_spec.rb
  spec/integrations/quickbooks_online/customers/create_spec.rb
  spec/integrations/quickbooks_online/customers/find_spec.rb
  spec/integrations/quickbooks_online/customers/searcher_spec.rb
  spec/integrations/quickbooks_online/customers/update_spec.rb
  spec/integrations/quickbooks_online/deposits/create_spec.rb
  spec/integrations/quickbooks_online/deposits/find_spec.rb
  spec/integrations/quickbooks_online/deposits/update_spec.rb
  spec/integrations/quickbooks_online/expenses/create_spec.rb
  spec/integrations/quickbooks_online/expenses/find_spec.rb
  spec/integrations/quickbooks_online/expenses/update_spec.rb
  spec/integrations/quickbooks_online/payments/create_spec.rb
  spec/integrations/quickbooks_online/payments/find_spec.rb
  spec/integrations/quickbooks_online/payments/update_spec.rb
  spec/integrations/quickbooks_online/vendors/create_spec.rb
  spec/integrations/quickbooks_online/vendors/find_spec.rb
  spec/integrations/quickbooks_online/vendors/searcher_spec.rb
  spec/integrations/quickbooks_online/vendors/update_spec.rb
  spec/support/quickbooks_helpers.rb
Labels: enhancement

#78 Fix stubbing
  spec/support/quickbooks_helpers.rb
Labels: bug

#87 Auto populate classification if missing
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/account_type.rb
  spec/integrations/quickbooks_online/accounts/create_spec.rb
  spec/support/quickbooks_helpers.rb
Labels: enhancement

#81 Add oauth helpers for connecting QBO and exchanging code for tokens
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/account_sub_type.rb
  lib/ledger_sync/resources/account.rb
  spec/adaptors/quickbooks_online/account/ledger_serializer_spec.rb
Labels: enhancement

#85 Add url helper for QBO
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  spec/adaptors/quickbooks_online/adaptor_spec.rb
Labels: enhancement

#94 Allow polymorphic entity on expense
  lib/ledger_sync/adaptors/quickbooks_online/deposit_line_item/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/operations/update.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/amount_type.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/entity_reference_type.rb
  lib/ledger_sync/adaptors/test/expense/operations/create.rb
  lib/ledger_sync/adaptors/test/expense/operations/find.rb
  lib/ledger_sync/adaptors/test/expense/operations/update.rb
  lib/ledger_sync/resources/deposit_line_item.rb
  lib/ledger_sync/resources/expense.rb
  lib/ledger_sync/type/reference_one.rb
  lib/ledger_sync/util/resources_builder.rb
  spec/adaptors/ledger_serializer_attribute_spec.rb
  spec/adaptors/operation_contract_spec.rb
  spec/adaptors/quickbooks_online/expense/ledger_serializer_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/create_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/find_spec.rb
  spec/adaptors/quickbooks_online/operations/expense/update_spec.rb
  spec/adaptors/test/operations/expense/create_spec.rb
  spec/adaptors/test/operations/expense/find_spec.rb
  spec/adaptors/test/operations/expense/update_spec.rb
  spec/integrations/quickbooks_online/deposits/create_spec.rb
  spec/integrations/quickbooks_online/expenses/create_spec.rb
  spec/integrations/quickbooks_online/expenses/find_spec.rb
  spec/integrations/quickbooks_online/expenses/update_spec.rb
  spec/integrations/test/expenses/create_spec.rb
  spec/integrations/test/expenses/find_spec.rb
  spec/integrations/test/expenses/update_spec.rb
  spec/resources/expense_spec.rb
  spec/support/input_helpers.rb
  spec/support/quickbooks_helpers.rb
  spec/util/resources_builder_spec.rb
Labels: enhancement
