Repository LedgerSync/ledger_sync, pull requests merged in 2020-03, with the labels that each got.

#166 Add NetSuite Department Resource
  lib/ledger_sync/adaptors/netsuite/department/ledger_serializer.rb
  lib/ledger_sync/adaptors/netsuite/department/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/department/operations/delete.rb
  lib/ledger_sync/adaptors/netsuite/department/operations/find.rb
  lib/ledger_sync/adaptors/netsuite/department/operations/update.rb
  lib/ledger_sync/adaptors/netsuite/department/searcher.rb
  spec/adaptors/netsuite/department/operations/create_spec.rb
  spec/adaptors/netsuite/department/operations/delete_spec.rb
  spec/adaptors/netsuite/department/operations/find_spec.rb
  spec/adaptors/netsuite/department/operations/update_spec.rb
  spec/adaptors/netsuite/department/searcher_spec.rb
  spec/factories/departments.rb
  spec/qa/netsuite/department_spec.rb
  spec/qa/support/shared_examples.rb
  spec/support/netsuite_helpers.rb
Labels: work in progress

#169 Fix dry validations
  lib/ledger_sync/adaptors/netsuite/account/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/currency/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/customer/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/department/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/vendor/operations/create.rb
Labels: bug

#170 DRY up NetSuite searchers and ledger resource overrides
  lib/ledger_sync/adaptors/adaptor.rb
  lib/ledger_sync/adaptors/netsuite/account/searcher.rb
  lib/ledger_sync/adaptors/netsuite/department/searcher.rb
  lib/ledger_sync/adaptors/netsuite/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  lib/ledger_sync/adaptors/searcher.rb
Labels: enhancement

#171 Add link to slack group
  README.md
Labels: enhancement
