Repository LedgerSync/ledger_sync, pull requests merged in 2020-01, with the labels that each got.

#118 Clean up tests
  spec/adaptors/netsuite_soap/adaptor_spec.rb
  spec/adaptors/operation_spec.rb
  spec/adaptors/quickbooks_online/expense/ledger_serializer_spec.rb
  spec/serializable/operation_spec.rb
  spec/serializable/resource_spec.rb
  spec/serializable/result_spec.rb
  spec/support/serializable_shared_examples.rb
Labels: enhancement

#116 Add support for FactoryBot in tests
  Gemfile.lock
  ledger_sync.gemspec
  spec/factories/accounts.rb
  spec/factories/bills.rb
  spec/factory_bot_spec.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/support/vcr.rb
Labels: enhancement

#119 Add NetSuite record metadata documentation
  .rubocop_todo.yml
  README.md
Labels: enhancement

#128 Add a helper method for creating an adaptor from ENV
  lib/ledger_sync/adaptors/netsuite/adaptor.rb
  lib/ledger_sync/adaptors/netsuite/record/metadata.rb
Labels: enhancement

#129 Use Request/Response objects for QBO adaptor
  lib/ledger_sync.rb
  lib/ledger_sync/adaptors/ledger_serializer.rb
  lib/ledger_sync/adaptors/ledger_serializer_type/references_many_type.rb
  lib/ledger_sync/adaptors/mixins/infer_adaptor_class_mixin.rb
  lib/ledger_sync/adaptors/mixins/infer_ledger_serializer_mixin.rb
  lib/ledger_sync/adaptors/mixins/infer_resource_class_mixin.rb
  lib/ledger_sync/adaptors/netsuite/operation/create.rb
  lib/ledger_sync/adaptors/netsuite_soap/operation/find.rb
  lib/ledger_sync/adaptors/netsuite_soap/operation/full_update.rb
  lib/ledger_sync/adaptors/netsuite_soap/operation/sparse_update.rb
  lib/ledger_sync/adaptors/netsuite_soap/searcher.rb
  lib/ledger_sync/adaptors/operation.rb
  lib/ledger_sync/adaptors/quickbooks_online/account/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  lib/ledger_sync/adaptors/quickbooks_online/bill/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/customer/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/department/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/deposit/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/expense/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/journal_entry/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_class/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_class/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/entity_reference_type.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation/create.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation/find.rb
  lib/ledger_sync/adaptors/quickbooks_online/operation/full_update.rb
  lib/ledger_sync/adaptors/quickbooks_online/request.rb
  lib/ledger_sync/adaptors/quickbooks_online/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/util/operation_error_parser.rb
  lib/ledger_sync/adaptors/quickbooks_online/vendor/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/webhook_event.rb
  lib/ledger_sync/adaptors/request.rb
  lib/ledger_sync/adaptors/response.rb
  lib/ledger_sync/adaptors/searcher.rb
  lib/ledger_sync/adaptors/stripe/adaptor.rb
  lib/ledger_sync/adaptors/stripe/operation/find.rb
  lib/ledger_sync/error/adaptor_errors.rb
  lib/ledger_sync/error/operation_errors.rb
  lib/ledger_sync/resource_attribute/dirty_mixin.rb
  spec/adaptors/netsuite_soap/customer/operations/find_spec.rb
  spec/adaptors/quickbooks_online/request_spec.rb
  spec/adaptors/quickbooks_online/searcher_spec.rb
  spec/adaptors/stripe/adaptor_spec.rb
  spec/fixtures/vcr_cassettes/LedgerSync_Adaptors_NetSuiteSOAP_Customer_Operations_Find/behaves_like_a_successful_operation/is_successful.yml
  spec/resources/dirty_spec.rb
  spec/support/ledger_serializer_helpers.rb
  spec/support/netsuite_soap_helpers.rb
  spec/util/resonad_spec.rb
Labels: enhancement

#134 Add NetSuite ops for currencies
  lib/ledger_sync.rb
  lib/ledger_sync/adaptors/netsuite/currency/deledger_serializer.rb
  lib/ledger_sync/adaptors/netsuite/currency/ledger_serializer.rb
  lib/ledger_sync/adaptors/netsuite/currency/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/currency/operations/delete.rb
  lib/ledger_sync/adaptors/netsuite/currency/operations/find.rb
  lib/ledger_sync/adaptors/netsuite/currency/operations/update.rb
  lib/ledger_sync/resources/bill.rb
  lib/ledger_sync/resources/bill_line_item.rb
  lib/ledger_sync/resources/currency.rb
  lib/ledger_sync/resources/customer.rb
  lib/ledger_sync/resources/department.rb
  lib/ledger_sync/resources/deposit.rb
  lib/ledger_sync/resources/deposit_line_item.rb
  lib/ledger_sync/resources/expense.rb
  lib/ledger_sync/resources/expense_line_item.rb
  lib/ledger_sync/resources/journal_entry.rb
  lib/ledger_sync/resources/journal_entry_line_item.rb
  lib/ledger_sync/resources/ledger_class.rb
  lib/ledger_sync/resources/payment.rb
  lib/ledger_sync/resources/transfer.rb
  lib/ledger_sync/resources/vendor.rb
  qa/netsuite/currency_spec.rb
  spec/adaptors/netsuite/currency/operations/create_spec.rb
  spec/adaptors/netsuite/currency/operations/delete_spec.rb
  spec/adaptors/netsuite/currency/operations/destroy_spec.rb
  spec/adaptors/netsuite/currency/operations/find_spec.rb
  spec/adaptors/netsuite/currency/operations/update_spec.rb
  spec/factories/currencies.rb
  spec/resources/expense_spec.rb
  spec/support/netsuite_helpers.rb
Labels: enhancement

#132 Add account operations for NetSuite
  lib/ledger_sync.rb
  lib/ledger_sync/adaptors/mixins/offset_and_limit_pagination_searcher_mixin.rb
  lib/ledger_sync/adaptors/netsuite/account/ledger_deserializer.rb
  lib/ledger_sync/adaptors/netsuite/account/ledger_serializer.rb
  lib/ledger_sync/adaptors/netsuite/account/operations/create.rb
  lib/ledger_sync/adaptors/netsuite/account/operations/find.rb
  lib/ledger_sync/adaptors/netsuite/account/searcher.rb
  lib/ledger_sync/adaptors/netsuite/searcher.rb
  lib/ledger_sync/adaptors/quickbooks_online/searcher.rb
  lib/ledger_sync/adaptors/searcher.rb
  qa/netsuite/account_spec.rb
  spec/adaptors/netsuite/account/operations/create_spec.rb
  spec/adaptors/netsuite/account/operations/destroy_spec.rb
  spec/adaptors/netsuite/account/operations/find_spec.rb
  spec/adaptors/netsuite/account/operations/update_spec.rb
  spec/adaptors/netsuite/account/searcher_spec.rb
  spec/factories/accounts.rb
  spec/support/netsuite_helpers.rb
Labels: enhancement, work in progress

#138 Add options to disable de/serialize for any attribute
  lib/ledger_sync/adaptors/ledger_serializer.rb
  lib/ledger_sync/adaptors/ledger_serializer_attribute.rb
  lib/ledger_sync/adaptors/ledger_serializer_attribute_set.rb
  lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer.rb
  spec/adaptors/ledger_serializer_spec.rb
Labels: enhancement

#142 Fix memoizing issue
  lib/ledger_sync/adaptors/mixins/infer_ledger_serializer_mixin.rb
  lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
  lib/ledger_sync/adaptors/quickbooks_online/request.rb
  spec/adaptors/quickbooks_online/operation_spec.rb
  spec/support/quickbooks_online_helpers.rb
  spec/support/test_adaptor_helpers.rb
Labels: bug

#145 Add dashboard helper url for LedgerClass
  lib/ledger_sync/adaptors/quickbooks_online/dashboard_url_helper.rb
Labels: enhancement

#147 Custom Attributes
  README.md
  lib/ledger_sync/adaptors/ledger_serializer.rb
  lib/ledger_sync/adaptors/mixins/infer_ledger_serializer_mixin.rb
  lib/ledger_sync/adaptors/mixins/infer_validation_contract_mixin.rb
  lib/ledger_sync/adaptors/netsuite/operation.rb
  lib/ledger_sync/adaptors/operation.rb
  lib/ledger_sync/adaptors/test/customer/ledger_serializer.rb
  lib/ledger_sync/adaptors/test/ledger_serializer.rb
  lib/ledger_sync/error.rb
  spec/adaptors/ledger_serializer_spec.rb
  spec/adaptors/operation_contract_spec.rb
  spec/adaptors/operation_spec.rb
  spec/resources_spec.rb
  spec/support/test_adaptor_helpers.rb
  spec/util/performer_spec.rb
Labels: enhancement

#144 Update QBO Stubs
  spec/adaptors/operation_spec.rb
  spec/adaptors/quickbooks_online/operation_spec.rb
  spec/adaptors/quickbooks_online/operations/customer/create_spec.rb
  spec/adaptors/quickbooks_online/operations/customer/find_spec.rb
  spec/adaptors/quickbooks_online/operations/customer/update_spec.rb
  spec/adaptors/quickbooks_online/webhook_event_spec.rb
  spec/spec_helper.rb
  spec/stubbing_spec.rb
  spec/support/operation_shared_examples.rb
  spec/support/quickbooks_online_helpers.rb
  spec/support/webmock_helpers.rb
Labels: enhancement, work in progress
